# Generated by Django 5.2.17 on 2026-09-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person leaving reflection', max_length=255)),
                ('verse', models.CharField(blank=True, default='', help_text='Referenced verse (optional)', max_length=255)),
                ('reflection', models.TextField(help_text='Personal reflection text (max 1000 chars)', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Submission timestamp')),
            ],
            options={
                'verbose_name': 'Reflection',
                'verbose_name_plural': 'Reflections',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(help_text='Chapter number (1-18)')),
                ('verse', models.IntegerField(help_text='Verse number')),
                ('sanskrit', models.TextField(help_text='Original Sanskrit text in Devanagari')),
                ('transliteration', models.TextField(help_text='Romanized transliteration of Sanskrit shloka')),
                ('english', models.TextField(help_text='English translation / meaning')),
                ('theme', models.CharField(db_index=True, help_text='Theme category (e.g. duty, soul, dharma)', max_length=100)),
            ],
            options={
                'verbose_name': 'Verse',
                'verbose_name_plural': 'Verses',
                'ordering': ['chapter', 'verse'],
            },
        ),
    ]
